// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropertyRentalManagement.Context;

#nullable disable

namespace PropertyRentalManagement.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropertyRentalManagement.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.AmenitiesInBuilding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AmenitiesInBuilding");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.AmenitiesNearby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AmenitiesNearby");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartmentNumber")
                        .HasColumnType("int");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsVacant")
                        .HasColumnType("bit");

                    b.Property<string>("Rooms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.ApartmentEquipmentsIncludedMappings", b =>
                {
                    b.Property<int>("EquipmentIncludedId")
                        .HasColumnType("int");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.HasKey("EquipmentIncludedId", "ApartmentId");

                    b.HasIndex("ApartmentId");

                    b.ToTable("ApartmentEquipmentsIncludedMappings");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.ApartmentOutdoorSpaceMappings", b =>
                {
                    b.Property<int>("OutdoorSpaceId")
                        .HasColumnType("int");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.HasKey("OutdoorSpaceId", "ApartmentId");

                    b.HasIndex("ApartmentId");

                    b.ToTable("ApartmentOutdoorSpaceMappings");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.ApartmentServiceIncludedMappings", b =>
                {
                    b.Property<int>("ServiceIncludedId")
                        .HasColumnType("int");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.HasKey("ServiceIncludedId", "ApartmentId");

                    b.HasIndex("ApartmentId");

                    b.ToTable("ApartmentServiceIncludedMappings");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.ApartmentTenantMappings", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateMovedIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateMovedOut")
                        .HasColumnType("datetime2");

                    b.HasKey("TenantId", "ApartmentId");

                    b.HasIndex("ApartmentId");

                    b.ToTable("ApartmentTenantMappings");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfApartments")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfFloors")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.BuildingAmemitiesInBuildingMappings", b =>
                {
                    b.Property<int>("AmenitiesInBuildingId")
                        .HasColumnType("int");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.HasKey("AmenitiesInBuildingId", "BuildingId");

                    b.HasIndex("BuildingId");

                    b.ToTable("BuildingAmenitiesInBuildingMappings");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.BuildingAmenitiesNearbyMappings", b =>
                {
                    b.Property<int>("AmenitiesNearbyId")
                        .HasColumnType("int");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.HasKey("AmenitiesNearbyId", "BuildingId");

                    b.HasIndex("BuildingId");

                    b.ToTable("BuildingAmenitiesNearbyMappings");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.BuildingOwnerMappings", b =>
                {
                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.HasKey("OwnerId", "BuildingId");

                    b.HasIndex("BuildingId");

                    b.ToTable("BuildingOwnerMappings");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.BuildingPropertyManagerMappings", b =>
                {
                    b.Property<int>("PropertyManagerId")
                        .HasColumnType("int");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.HasKey("PropertyManagerId", "BuildingId");

                    b.HasIndex("BuildingId");

                    b.ToTable("BuildingPropertyManagerMappings");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.EquipmentIncluded", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EquipmentsIncluded");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("ArePetsAllowed")
                        .HasColumnType("bit");

                    b.Property<string>("AvailableFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSmokingAllowed")
                        .HasColumnType("bit");

                    b.Property<string>("LeaseDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("CreatorId");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.OutdoorSpace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OutdoorSpaces");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.ServiceIncluded", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServicesIncluded");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.UserRoleMappings", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoleMappings");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.Apartment", b =>
                {
                    b.HasOne("PropertyRentalManagement.Models.Building", "Building")
                        .WithMany("Apartments")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.ApartmentEquipmentsIncludedMappings", b =>
                {
                    b.HasOne("PropertyRentalManagement.Models.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyRentalManagement.Models.EquipmentIncluded", "EquipmentIncluded")
                        .WithMany()
                        .HasForeignKey("EquipmentIncludedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("EquipmentIncluded");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.ApartmentOutdoorSpaceMappings", b =>
                {
                    b.HasOne("PropertyRentalManagement.Models.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyRentalManagement.Models.OutdoorSpace", "OutdoorSpace")
                        .WithMany()
                        .HasForeignKey("OutdoorSpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("OutdoorSpace");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.ApartmentServiceIncludedMappings", b =>
                {
                    b.HasOne("PropertyRentalManagement.Models.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyRentalManagement.Models.ServiceIncluded", "ServiceIncluded")
                        .WithMany()
                        .HasForeignKey("ServiceIncludedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("ServiceIncluded");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.ApartmentTenantMappings", b =>
                {
                    b.HasOne("PropertyRentalManagement.Models.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyRentalManagement.Models.User", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.Building", b =>
                {
                    b.HasOne("PropertyRentalManagement.Models.Address", "Address")
                        .WithOne("Building")
                        .HasForeignKey("PropertyRentalManagement.Models.Building", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.BuildingAmemitiesInBuildingMappings", b =>
                {
                    b.HasOne("PropertyRentalManagement.Models.AmenitiesInBuilding", "AmenitiesInBuilding")
                        .WithMany()
                        .HasForeignKey("AmenitiesInBuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyRentalManagement.Models.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AmenitiesInBuilding");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.BuildingAmenitiesNearbyMappings", b =>
                {
                    b.HasOne("PropertyRentalManagement.Models.AmenitiesNearby", "AmenitiesNearby")
                        .WithMany()
                        .HasForeignKey("AmenitiesNearbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyRentalManagement.Models.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AmenitiesNearby");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.BuildingOwnerMappings", b =>
                {
                    b.HasOne("PropertyRentalManagement.Models.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyRentalManagement.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.BuildingPropertyManagerMappings", b =>
                {
                    b.HasOne("PropertyRentalManagement.Models.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyRentalManagement.Models.User", "PropertyManager")
                        .WithMany()
                        .HasForeignKey("PropertyManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("PropertyManager");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.Listing", b =>
                {
                    b.HasOne("PropertyRentalManagement.Models.Apartment", "Apartment")
                        .WithMany("Listings")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyRentalManagement.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.UserRoleMappings", b =>
                {
                    b.HasOne("PropertyRentalManagement.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyRentalManagement.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.Address", b =>
                {
                    b.Navigation("Building");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.Apartment", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.Building", b =>
                {
                    b.Navigation("Apartments");
                });
#pragma warning restore 612, 618
        }
    }
}
